### PR TITLE
Switched mcrypt to openssl

### PR DESCRIPTION
**Pull request by smoked**
Switched mcrypt to openssl, because mcrypt has been deprecated as of PHP 7.1.0

### CODE REVIEW

**Review by axzx — APPROVED** [review]

**Comment by axzx** [comment]
@ambta @marcel-ambta can you merge this PR?

**Comment by BboyKeen** [comment]
Be careful as we had some issues with old encrypted data. The new implementation breaks the decryption of old values because Rijndael 256 is not the same as AES-256.

Take a look at this extract for further information : Also, MCRYPT_RIJNDAEL_256 is not AES-256, it's a different variant of the Rijndael block cipher. If you want AES-256 in mcrypt, you have to use MCRYPT_RIJNDAEL_128 with a 32-byte key. OpenSSL makes it more obvious which mode you are using (i.e. 'aes-128-cbc' vs 'aes-256-ctr'). (First user contributed note : http://php.net/manual/en/function.mcrypt-encrypt.php)

**Review by ersin-demirtas — APPROVED** [review]
These changes look good, when is this going to be merged?

**Comment by tulik** [comment]
Just a suggestion - as it's a @vmelnik-ukraine work, shouldn't it be merged to the origin? 

*NOTE:* [What happens to forks when a repository is deleted or changes visibility?](https://help.github.com/en/articles/what-happens-to-forks-when-a-repository-is-deleted-or-changes-visibility)

**Pull request merged**
